### ISSUE TITLE
Select max instance not working

### ISSUE THREAD

**Issue by benjaminfichet** [cb109/sublime3dsmax#16]
The select max instance is not working for us..

The class SelectMaxInstanceCommand runs :
sublime.active_window().show_quick_panel(items, on_select, 0,last_index, **on_highlighted**)
but the **on_highlighted** is defined to pass. 

Calling sublime.active_window().show_quick_panel without the on_highlighted callbacks seems to fix the issue. 

Not sure if changing this would break anything tho.

**Comment by cb109** [comment]
Hi Benjamin, thanks for the report. I have some questions for you:

* Can you please give me a copypasta or a screenshot of the Sublime console (`View > Show Console`) when this fails for you?
* Which Sublime build are you using (See `Help > About Sublime Text`)
* Which 3ds Max version are you trying to connect to?

`on_highlighted` is just given to satisfy the window API, but I did not want to execute anything when you hover an item, only on selection, so that should be fine. Maybe the API has changed, will look into that.

**Comment by cb109** [comment]
@benjaminfichet I'd love to look into this, yet it would really help to know the Sublime and Max versions that you had problems with :)

**Comment by benjaminfichet** [comment]
Sorry for the late reply, I was pretty busy.I'll check the issue tomorrow and provide you the details.

**Comment by cb109** [comment]
Closing for now, feel free to reopen with some details anytime.
