### ISSUE TITLE
MXS Code folding/collapsing

### ISSUE THREAD

**Issue by johanboekhoven** [cb109/sublime3dsmax#17]
I can't remember if this was mentioned anywhere already, but here it goes.
Code folding doesn't always work correctly. I found the biggest issue to be that commenting ( ctrl+/ ) always happens at the start of the line, this seems to confuse the folding functionality.

So I think there's 2 possible fixes, look into the folding code and see if anything can be done, or (and I like this better) make sure commenting is in front of the text and not at the start of the line. Not sure if that breaks any coding conventions, but I like commenting better in front of the actual word instead of the line.

**Comment by cb109** [comment]
Hi @johanboekhoven and sorry for neglecting this ticket for over a damn year :] For your first suggestion: That would probably require to to tap into the maxscript language definition, and that is a complicated thing and  could be lots of work for little benefit (same as for #1). The definition pretty much does 90% of what one would ever want, which personally is good enough for me to leave it as is, since it has been a contribution by someone else anyway.

I am not sure if we can do fix no. 2 also not sure if I'd like that as I think this looks clumsy:
```javascript
-- function foobar = (
  -- LayerManager....
  -- for obj in objects do
    -- obj.wirecolor + ...
-- )
```
I personally never use the code folding options in sublime, so it is very unlikely I'll have the motivation to work on this, thus closing. Please feel free to reopen if you still strongly feel this needs fixing. Thanks for your input!

**Comment by cb109** [comment]
Please see https://github.com/cb109/sublime3dsmax#formatting-of-inline-comments on how to customize comment formatting.
