### ISSUE TITLE
File path encoding issue special character

### ISSUE THREAD

**Issue by arsenevandebilt** [cb109/sublime3dsmax#21]
My personal name contains a special symbol (**è**) and **sublime3dsmax (v0.9.8)** with **Sublime Text 2.0.2 (Build 2221)** on **Windows 10 (Version 1803; Build 17134.48)** can not deal with that in the file path.

When I send a file, the command received in the **3ds Max 2017** MAXScript Listener ends up wrongly encoded: `fileIn @"C:\Folder\ArsÃ¨ne\file.ms"`

Which then 3ds Max can not find:
```
-- Runtime error: fileIn: can't open file - "C:\Folder\ArsÃ¨ne\file.ms"
-- MAXScript callstack:
--	thread data: threadID:14740
--	------------------------------------------------------
--	[stack level: 0]
--	In top-level
```

**Solution:**
Removing/commenting out **line 132** `cmd = cmd.encode("utf-8")  # Needed for ST3!` from **sublime3dsmax.py** solves this issue for me in **Sublime Text 2**.

**MAXScript Listener:**
`fileIn @"C:\Folder\Arsène\file.ms"`

**Comment by cb109** [comment]
Hi @drdelta and thanks for the report! I think it should be simple to implement, but the problem is I am thinking of dropping Sublime 2 support as it is pretty much deprecated and makes testing things that much more time consuming.

Any good reason I should keep Sublime 2 support? You should upgrade, it's great :) You won't need half your addons as they are now already builtin.

**Comment by arsenevandebilt** [comment]
I would be fine with dropping support for Sublime Text 2, I've recently switched over anyway.

You could consider releasing a "final" Sublime Text 2 version of your plugin which resolves this issue, but does not get any further updates.

**Comment by cb109** [comment]
True, I will consider that. Thank you for your feedback.
